sonar.projectKey=projet-docker-angular
sonar.projectName=Projet Docker Angular
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
