- name: Checkout code
  uses: actions/Checkout@v3
  with:
    fetch-depth: 0          # historique Git complet, requis par Sonar
 
- name: SonarQube Scan
  uses: sonarsource/sonarqube-scan-action@v5
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
